### ISSUE TITLE
Blank visualisation even though algorithm(s) run correctly

### ISSUE THREAD

**Issue by shern2** [neo4j-devtools/neuler#106]
Hi, I am going through several simple tutorials under Graph Academy e.g. [Connected Components in NEuler](https://www.youtube.com/watch?v=eu7HBaPev7A), but while the algorithms like WCC run ok and outputs a table:
![image](https://user-images.githubusercontent.com/18212522/102984220-3a1ef000-4548-11eb-9b2d-985459124ab7.png)

The `visualisation` tab is just blank regardless of whether I hit the `Refresh` button or change the other settings:
![image](https://user-images.githubusercontent.com/18212522/102984286-56229180-4548-11eb-8451-b4eed72dea33.png)

I am running Neo4j Desktop 1.3.11, and my other settings are:
![image](https://user-images.githubusercontent.com/18212522/102984360-6f2b4280-4548-11eb-855a-9dd5f28acbe8.png)

**Comment by tomasonjo** [comment]
Sorry for the late reply. I have tried the simple example and it looks to be working. Can you please let me know if the problem persists?

Thanks

**Comment by shern2** [comment]
I have retried on Neo4j Desktop 1.4.5. The visualization works now.
Thanks.
