### ISSUE TITLE
Graph Data Science Error (APOC Metadata Procedure Unavailable)

### ISSUE THREAD

**Issue by JuSte94** [neo4j-devtools/neuler#131]
Hello neo4j community,

I have the following error described here in [Stackoverflow](https://stackoverflow.com/questions/68321790/graph-data-science-error-apoc-metadata-procedure-unavailable).

I did the import of the [files](https://www.dropbox.com/s/gkidqx6dkggc3p4/commits-packages-relationship.zip?dl=0) with neo4j-admin like this:

`bin/neo4j-admin import --database=neo4j --id-type=INTEGER --multiline-fields=true --skip-duplicate-nodes --skip-bad-relationships=true --nodes=commits=import/nodes-commits.csv --nodes=packages=import/nodes-packages.csv --relationships=commits=import/relationship-projects_commits.csv`

When I skip the relationship, the error disappeared.

The security.log has one error:

`2021-07-12 21:29:40.855+0000 ERROR {plugin-com.neo4j.plugin.jwt.auth.JwtAuthPlugin} Invalid serialized unsecured/JWS/JWE object: Missing part delimiters`

Thanks for the help :)

**Comment by tomasonjo** [comment]
Can you also provide your Neo4j and APOC versions?
Thanks

**Comment by JuSte94** [comment]
- Neo4j Desktop 1.4.7
- APOC 4.3.0.0
- GDSL 1.6.1

**Comment by tomasonjo** [comment]
And your Neo4j database instance version? Btw... do you install plugins using the Desktop installation option?

**Comment by JuSte94** [comment]
- DBMS: 4.3.2

Yes I'm using the Plugins in the Desktop version.

**Comment by JuSte94** [comment]
The problem was that the name of the relationship was already used for a node. I changed the name for the relationship and now it works.

Seems that GDSL also needs different labels for the nodes and relationships.

**Comment by tomasonjo** [comment]
I've tested this issue with (:Node)-[:Node]->(:Node) graph, and NEuler worked just fine... not exactly sure, I've also added a whitespace into node label, but it still worked.
