### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hygorxaraujo** [neo4j-devtools/neuler#147]
Every time I try to install the Graph Data Science Playground from the apps gallery it ends up installing an "app" with the title MyJFrog.
![image](https://user-images.githubusercontent.com/4503257/199080821-81f9fdfc-c108-4086-b784-bcd42324fef5.png)

If I try to open this "app" it only shows the following window:
![image](https://user-images.githubusercontent.com/4503257/199081152-4d97e6da-bef5-4cec-8471-723e77adeb9e.png)

If I try to access the address from a browser it gets me to the following page:
![image](https://user-images.githubusercontent.com/4503257/199080670-2cf0c670-b737-45e0-a67f-0f57311bd7e6.png)

**Comment by mariaemancipium** [comment]
I'm having the same issue. I even tried building the package myself from this repo but I had a lot of difficulty installing all the dependencies. Has this project been abandoned, I wonder?

**Comment by mariaemancipium** [comment]
Looking more closely: MyJFrog appears to be some sort of package repository (see screenshot), and I also saw it referenced in the yarn.lock file as the source of the dependencies. So maybe its the server that hosts the dependencies that's down? I'll let you know if I figure out a workaround...

![image](https://user-images.githubusercontent.com/82241435/199316068-a9c97477-5f67-4791-8967-b788eb71b329.png)

**Comment by mariaemancipium** [comment]
In fact - paid even more attention as I went to build the package: For each dependency, its trying to download them from myjfrog... and it says the packages are corrupted. So we need to find another source for the deps...
![image](https://user-images.githubusercontent.com/82241435/199316416-f275a05c-cf79-4668-9e7e-f3e1dec2e843.png)

**Comment by mariaemancipium** [comment]
Ok so here's a bit more of an update. I found that I can force it out of using jfrog as a repository. So if you clone this repo, and cd into the project's folder, you can run `npm install --registry https://registry.npmjs.org` and it will install 90% of the packages... it just won't find the one for the app: graph-app-kit. For that, you need to pull it from github by running `npm install graph-app-kit https://github.com/neo4j-devtools/graph-app-kit`

However, I'm having the darndest time installing the components of graph-app-kit. When I try to build this project by running `npm run build` it fails saying that its missing graph-app-kit/components/GraphAppBase.

From that point, I was able to actually just copy the entire folder "Components" from the Graph-app-kit repo into the neuler/node-packages/graph-app-kit folder, and it didn't error out for missing things... but then it gave me some error about not being able to parse jsx files. sigh.

**Comment by mariaemancipium** [comment]
I reached out to Neo4J and @nglgzz , the dev administrating this repo. He told me the team is working on the issue, but for now has republished Neuler to the main npm registry: 

> The team responsible for the Neuler tool is looking into it. For now the package has been published at https://registry.npmjs.org/neuler (you can paste this URL in Neo4j Desktop to install the graph app).

I did this and Neuler is now working for me!

**Comment by nglgzz** [comment]
Happy to hear you got Neuler to work in the end! Just want to clarify though, that I'm not the admin of this repo, I just happen to contribute to other repos within the neo4j-devtools organization.

**Comment by mariaemancipium** [comment]
> Happy to hear you got Neuler to work in the end! Just want to clarify though, that I'm not the admin of this repo, I just happen to contribute to other repos within the neo4j-devtools organization.

Got it. Thanks even more for your help, then!

**Comment by hygorxaraujo** [comment]
Thank you, everyone! I managed to install it with the new link https://registry.npmjs.org/neuler
