### ISSUE TITLE
Not working with neo4j 5?

### ISSUE THREAD

**Issue by stellasia** [neo4j-devtools/neuler#149]
Hello,

Trying to use latest version (0.1.55)

It fails at startup (well, it hangs indefinitely) at this stage:
```
CALL dbms.procedures()
YIELD name
WHERE name STARTS WITH "gds"
RETURN count(*) AS count;
```

which I guess should be replaced with Neo 5 by something like:

```
CALL dbms.procedures()
YIELD name
WHERE name STARTS WITH "gds"
RETURN count(*) AS count;
```

The main question is: is there any plan to update the lib to newer Neo4j version? Because I am definitely not sure this will be the only required change.

Thanks.
Estelle

**Comment by tomasonjo** [comment]
Hi Estelle, 

thanks for reporting the issue. It seems that APOC and GDS verification seems to be the only issues in Neo4j V5 as everything else is tied to GDS procedures which haven't changed. I've added a PR to change the mentioned issue, however I don't have the access to release new versions to Desktop and Sandbox. I will let you know once it gets done.

Thanks

**Comment by stellasia** [comment]
Hello hello,

I see that @tomasonjo 's PR was merged. Any chance we can get a new release soon? 

Thanks

**Comment by tomasonjo** [comment]
Hi @stellasia, sorry for the late reply. There was a dependency issue to some package that are not available anymore.
Anyhow, I how fixed that and also added Sample graph support for v5 Cypher syntax, so once https://github.com/neo4j-devtools/neuler/pull/152 is merged, a new version of Neuler should be published

**Comment by tomasonjo** [comment]
A new version has been published and should work with Neo4j v5. Can you test it on your end, just to make sure.

Thanks

**Comment by stellasia** [comment]
Hey @tomasonjo,

Yes, confirmed, the new version is working for my database using Neo4j 5, thanks a lot!
