### ISSUE TITLE
JavaScript issue with Cypher generating floating instead of integer when using LIMIT in query

### ISSUE THREAD

**Issue by musachi** [neo4j-devtools/neuler#151]
nothing

**Comment by tomasonjo** [comment]
Hi Musachi,

This is not an appropriate repository for JS driver issues.
Please post your issue on the JS driver repository, which is available at: https://github.com/neo4j/neo4j-javascript-driver

**Comment by musachi** [comment]
Sorry my friend, I noticed that, after I published. Sorry Sorry.

**Comment by tomasonjo** [comment]
No problem. I'll close this issue.
