### ISSUE TITLE
Louvain runs but LPA errors

### ISSUE THREAD

**Issue by ghost** [neo4j-devtools/neuler#69]
When I try to run LPA, I get this error. But Louvain runs successfully.
```
Algorithm failed to complete Neo4jError: Can't coerce `Map{writeProperty -> String("lpa"), defaultValue -> Double(1.000000e+00), concurrency -> Double(8.000000e+00), direction -> String("Both")}` to String
```
Perhaps my edge or node attributes are unparseable?

**Comment by tomasonjo** [comment]
Closing this issue. Please let us know if the issue persists with the new version
