### ISSUE TITLE
make auto-generated match query take config into account 

### ISSUE THREAD

**Issue by jexp** [neo4j-devtools/neuler#76]
```MATCH (node)
WHERE not(node[$config.writeProperty] is null)
RETURN node, node[$config.writeProperty] AS score
ORDER BY score DESC
LIMIT toInteger($limit)
```
should be

```MATCH (node:`Person`)
WHERE exists(node.degree)
RETURN node.degree as score
ORDER BY score DESC
LIMIT toInteger($limit)
```

**Comment by tomasonjo** [comment]
This was fixed with the code:

https://github.com/neo4j-devtools/neuler/blob/master/src/services/queries.js#L17
