### ISSUE TITLE
JavaScript issue with floating point number vs integer in generated Cypher query

### ISSUE THREAD

**Issue by Mats-SX** [neo4j-devtools/neuler#77]
Originally raised in https://github.com/neo4j/graph-data-science/issues/47

When specifying a `LIMIT` in the UI, the generated query sends a floating point number in the Cypher query, which is not allowed. The parameter to `LIMIT` must be an integer.

![Issue](https://user-images.githubusercontent.com/24269034/82915330-dfe98c80-9f70-11ea-9740-53382cad8790.png)

**Comment by yeus** [comment]
same problem here. I use Neo4j Vesion 4.0.4 and neuler But then copying the code for the parameters into neo4j this also doesn't work and I get an error: 

```
Syntax error at line 2 col 0:

  :param config => ({
  ^
Unexpected "\n". 
```

**Comment by tomasonjo** [comment]
Sorry for the late reply, this issue was fixed and now simply uses

```
RETURN node, score
ORDER BY score DESC
LIMIT toInteger($limit);
```

If the problem persists, please open a new issue
